version: '3.7'
services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'ediarista'
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ./db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html